### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by alanchenyx** [victorskl/git-tute#3]
add feature alan-workflow

**Comment by victorskl** [comment]
@alanchenyx Please try to avoid using the same (exact) topic name, including the closed issue ticket. You should check this in prior in the [Project Kanban Board](https://github.com/victorskl/git-tute/projects/1), as commented in #5. In this case, [`Workflow`](https://github.com/victorskl/git-tute/issues/1) is already used/created before; and has the status of "closed" or "resolved". Therefore, if you want to create a new issue ticket that is related to the existing/existed [`Workflow`](https://github.com/victorskl/git-tute/issues/1), the next scenario could be `Workflow-regression` or `Workflow-reenact` or `Workflow-typo-bug` or so on. Based on what you written there in your comment, this issue ticket title should be `alan-workflow` or `workflow-alan` or `alan-test` or any combination of these. Or totally a new one like `my-foo-feature`.
