### ISSUE TITLE
Workflow/bug

### ISSUE THREAD

**Issue by alanchenyx** [victorskl/git-tute#5]
Please merge #3, after that, please create a bug branch and delete the useless text "alan has viewed this page". And send alanchenyx a pull request!

**Comment by victorskl** [comment]
@alanchenyx Remember, namespacing like `bug/xxxx` or `feature/xxxx` only require during Git Workflow's topic branch creation. For the issue title, you can formulate just a "topic" name itself. This issue title naming could also derive from a [**user story**](https://www.google.com.au/search?q=user+story) or a [**use case**](https://www.google.com.au/search?q=use+case).

When creating a issue ticket, it does not require to follow bug or feature prefixes. Also note that these are definitely not suffixes i.e. not `Workflow\bug`. So, please fix the issue ticket title to the topic name that you would like to do for your user story or use case.

**Comment by victorskl** [comment]
@alanchenyx Also, remember to associate any issue ticket to the [Project Kanban Board](https://github.com/victorskl/git-tute/projects/1). You should associate the issue ticket to appropriate Kanban Board column (at top right corner > Add cards). This brings the issue on the board, i.e. to the team view. And also, this will make you check the topic collision, such that, no two developers is creating the same issue ticket for the given topic, including the closed issue tickets.
